language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "nightly"
# command to install dependencies
install:
  - "pip install --trusted-host www.edna-site.org -r requirements_travis.txt"
  - "python info_platform.py"
  - "python setup.py build install"
# command to run tests
script: 
  - "python setup.py build test"
  - "(cd /tmp && python -c 'import fabio, sys; print(sys.version); fabio.tests()')"
