version: 0.7-dev{build}

# fetch repository as zip archive
shallow_clone: true

notifications:
- provider: Email
  to:
  - silx-ci@edna-site.org
  subject: '[CI] appveyor'
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_BUILD_DIR: "venv_build"
        VENV_TEST_DIR: "venv_test"

    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.10"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python27-x64"
          PYTHON_VERSION: "2.7.10"
          PYTHON_ARCH: "64"

        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python34-x64"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "64"

install:
  # Add Python to PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"print(tuple.__itemsize__*8)\""
  # Install the build and runtime dependencies of the project.
  - "pip install --upgrade pip --user"
  - "pip install --trusted-host www.silx.org -r ci\\requirements_appveyor.txt"
  - "python setup.py build test"
  - "python setup.py bdist_wheel bdist_msi"
  - ps: "ls dist"
  # Install the generated wheel package to test it
  - "pip install --pre --find-links dist/ fabio"

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - "python run_tests.py"
  - "python run_tests.py --installed"
  - "mkdir empty_folder"
  - "cd empty_folder"

  - "python -c \"import fabio; fabio.tests()\""

  # Move back to the project folder
  - "cd .."

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

